# Stage 1
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /

# Restore
COPY ["./FitnessTracker.csproj", "/FitnessTracker"]
RUN dotnet restore '/FitnessTracker/FitnessTracker.csproj'

# Build
COPY ["./", "/FitnessTracker"]
RUN dotnet build '/FitnessTracker/FitnessTracker.csproj' -c Release -o /app/build

# Stage 2
FROM build AS publish
RUN dotnet publish '/FitnessTracker/FitnessTracker.csproj' -c Release -o /app/publish

# Stage 3
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=4001
EXPOSE 4001
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "FitnessTracker.dll" ]
